spring.application.name=backend
server.port=8080
logging.level.com.poulastaa.backend=INFO
# Serialize Instant/Date as ISO-8601 strings (easier for JS to parse)
spring.jackson.serialization.write-dates-as-timestamps=false
